// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	config "github.com/winyx/backend/dashboard_gateway/internal/handler/config"
	health "github.com/winyx/backend/dashboard_gateway/internal/handler/health"
	monitoring "github.com/winyx/backend/dashboard_gateway/internal/handler/monitoring"
	stats "github.com/winyx/backend/dashboard_gateway/internal/handler/stats"
	"github.com/winyx/backend/dashboard_gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// システム設定情報の取得
				Method:  http.MethodGet,
				Path:    "/config",
				Handler: config.ConfigInfoHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/dashboard"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// システム全体のヘルスチェック
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: health.SystemHealthHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/dashboard"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// リアルタイムメトリクスの取得
				Method:  http.MethodGet,
				Path:    "/metrics/realtime",
				Handler: monitoring.RealtimeMetricsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/dashboard"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// API使用統計の取得
				Method:  http.MethodGet,
				Path:    "/stats",
				Handler: stats.ApiStatsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/dashboard"),
	)
}
