// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	org "user_service/internal/handler/org"
	"user_service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/users/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/users/register",
				Handler: RegisterHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/info",
				Handler: UserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/profile",
				Handler: UpdateProfileHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/admin/users",
				Handler: UserListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/admin/users",
				Handler: UserCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/admin/users/:id",
				Handler: UserDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/v1/admin/users/:id",
				Handler: UserUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/v1/admin/users/:id",
				Handler: UserDeleteHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/orgs",
				Handler: org.CreateOrgHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/orgs",
				Handler: org.ListMyOrgsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/orgs/:id",
				Handler: org.GetOrgHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/orgs/:id",
				Handler: org.UpdateOrgHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/orgs/:id",
				Handler: org.DeleteOrgHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/orgs/:id/members",
				Handler: org.AddOrgMemberHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/orgs/:id/members/:userId",
				Handler: org.RemoveOrgMemberHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)
}
