// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sessionsFieldNames          = builder.RawFieldNames(&Sessions{})
	sessionsRows                = strings.Join(sessionsFieldNames, ",")
	sessionsRowsExpectAutoSet   = strings.Join(stringx.Remove(sessionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sessionsRowsWithPlaceHolder = strings.Join(stringx.Remove(sessionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheSessionsIdPrefix = "cache:sessions:id:"
)

type (
	sessionsModel interface {
		Insert(ctx context.Context, data *Sessions) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Sessions, error)
		Update(ctx context.Context, data *Sessions) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultSessionsModel struct {
		sqlc.CachedConn
		table string
	}

	Sessions struct {
		Id        uint64    `db:"id"`
		UserId    uint64    `db:"user_id"`    // ユーザーID
		Token     string    `db:"token"`      // セッショントークン
		ExpiresAt time.Time `db:"expires_at"` // 有効期限
		CreatedAt time.Time `db:"created_at"` // 作成日時
	}
)

func newSessionsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSessionsModel {
	return &defaultSessionsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`sessions`",
	}
}

func (m *defaultSessionsModel) Delete(ctx context.Context, id uint64) error {
	sessionsIdKey := fmt.Sprintf("%s%v", cacheSessionsIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, sessionsIdKey)
	return err
}

func (m *defaultSessionsModel) FindOne(ctx context.Context, id uint64) (*Sessions, error) {
	sessionsIdKey := fmt.Sprintf("%s%v", cacheSessionsIdPrefix, id)
	var resp Sessions
	err := m.QueryRowCtx(ctx, &resp, sessionsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sessionsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSessionsModel) Insert(ctx context.Context, data *Sessions) (sql.Result, error) {
	sessionsIdKey := fmt.Sprintf("%s%v", cacheSessionsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, sessionsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.Token, data.ExpiresAt)
	}, sessionsIdKey)
	return ret, err
}

func (m *defaultSessionsModel) Update(ctx context.Context, data *Sessions) error {
	sessionsIdKey := fmt.Sprintf("%s%v", cacheSessionsIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sessionsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.Token, data.ExpiresAt, data.Id)
	}, sessionsIdKey)
	return err
}

func (m *defaultSessionsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheSessionsIdPrefix, primary)
}

func (m *defaultSessionsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sessionsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSessionsModel) tableName() string {
	return m.table
}
