// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type Request struct {
	Name string `path:"name,optional,default=you"`
}

type Response struct {
	Message string `json:"message"`
}

type LoginReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginRes struct {
	AccessToken string `json:"access_token"`
	ExpireTime  int64  `json:"expire_time"`
}

type RegisterReq struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type RegisterRes struct {
	Id    int64  `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

type UserInfoRes struct {
	Id    int64  `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

type UserListReq struct {
	Page  int64 `form:"page,optional,default=1"`
	Limit int64 `form:"limit,optional,default=10"`
}

type UserListRes struct {
	Users []UserInfo `json:"users"`
	Total int64      `json:"total"`
	Page  int64      `json:"page"`
	Limit int64      `json:"limit"`
}

type UserInfo struct {
	UserId    int64    `json:"user_id"`
	Name      string   `json:"name"`
	Email     string   `json:"email"`
	Status    string   `json:"status"`
	Roles     []string `json:"roles,omitempty"`
	CreatedAt string   `json:"created_at"`
	UpdatedAt string   `json:"updated_at"`
}

type UserDetailReq struct {
	UserId int64 `path:"id"`
}

type UserDetailRes struct {
	User UserInfo `json:"user"`
}

type UserUpdateReq struct {
	UserId int64  `path:"id"`
	Name   string `json:"name"`
	Email  string `json:"email"`
	Status string `json:"status,optional"`
}

type UserUpdateRes struct {
	User UserInfo `json:"user"`
}
